aws-iot/securedapp/app/urls.py
from django.conf.urls import url
from . import views
app_name = 'app'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signout$', views.signout, name='logout'),
    url(r'^temperature$', views.setTemp, name='temperature'),
    url(r'^light$', views.setLight, name='light'),
    url(r'^refresh$', views.refresh, name='refresh'),
    url(r'^mode$', views.setMode, name='mode')
]

aws-iot/securedapp/securedapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aws-iot/securedapp/app/templates/app/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>Security</title>

    <meta name="description" content="">

    <link href="{% static 'app/assets/css/preload.css' %}" rel="stylesheet">
    <link href="{% static 'app/assets/css/vendors.css' %}" rel="stylesheet">
    <link href="{% static 'app/assets/css/syntaxhighlighter/shCore.css' %}" rel="stylesheet" >
    <link href="{% static 'app/assets/css/style-blue.css' %}" rel="stylesheet" title="default">
    <link href="{% static 'app/assets/css/width-full.css' %}" rel="stylesheet" title="default">
</head>

<!-- Preloader -->
<div id="preloader">
    <div id="status">&nbsp;</div>
</div>

<body>

<div class="paper-back-full">
    <div class="login-form-full">
        <div class="fix-box">
            <div class="text-center title-logo animated fadeInDown animation-delay-5">Dashboard<span>&nbsp;Access</span></div>
            <div class="transparent-div no-padding animated fadeInUp animation-delay-8">
                <ul class="nav nav-tabs nav-tabs-transparent">
                    <li class="active" style="width: 100%; text-align: center"><a href="#home" data-toggle="tab">Login</a></li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active" id="home">
                        <form role="form" action="{% url 'app:signin' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group login-input">
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                    <input required type="email" name="email" class="form-control" placeholder="Email">
                                </div>
                                <br>
                                <div class="input-group login-input">
                                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                    <input required type="password" name="password" class="form-control" placeholder="Password">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-ar btn-primary pull-left">Login</button>
                                    &nbsp;&nbsp;&nbsp;If you don't have an account yet, you can <a href="{% url 'app:signup' %}">register here</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'app/assets/js/vendors.js' %}"></script>
<script src="{% static 'app/assets/js/syntaxhighlighter/shCore.js' %}"></script>
<script src="{% static 'app/assets/js/app.js' %}"></script>
<script src="{% static 'app/assets/js/holder.js' %}"></script>
<script src="{% static 'app/js/home_login_full.js' %}"></script>
<script src="{% static 'app/js/notify.js' %}"></script>

{% if messages %}
    <script>
        jQuery(document).ready(function () {
            {% for message in messages %}
                jQuery.notify({
                    message: '{{ message }}'
                },{
                    type: 'danger',
                    placement: {
                        from: "top",
                        align: "center"
                    }
                });
            {% endfor %}
        });
    </script>
{% endif %}
</body>

</html>

aws-iot/securedapp/app/templates/app/signup.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>Security</title>

    <meta name="description" content="">

    <!-- CSS -->

    <link href="{% static 'app/assets/css/preload.css' %}" rel="stylesheet">
    <link href="{% static 'app/assets/css/vendors.css' %}" rel="stylesheet">
    <link href="{% static 'app/assets/css/syntaxhighlighter/shCore.css' %}" rel="stylesheet" >
    <link href="{% static 'app/assets/css/style-blue.css' %}" rel="stylesheet" title="default">
    <link href="{% static 'app/assets/css/width-full.css' %}" rel="stylesheet" title="default">
</head>

<!-- Preloader -->
<div id="preloader">
    <div id="status">&nbsp;</div>
</div>

<body>

<div class="paper-back-full">
    <div class="login-form-full">
        <div class="fix-box">
            <div class="text-center title-logo animated fadeInDown animation-delay-5" style="background-image: none">Dashboard<span>&nbsp;Sign up</span></div>
            <div class="transparent-div no-padding animated fadeInUp animation-delay-8">
                <ul class="nav nav-tabs nav-tabs-transparent">
                    <li class="active" style="width: 100%; text-align: center"><a href="#profile" data-toggle="tab">Register</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active" id="profile">
                        <form role="form" action="{% url 'app:signup' %}" method="post">
                            {% csrf_token %}
                            <div class="input-group login-input">
                                <span class="input-group-addon"><i class="fa fa-at"></i></span>
                                <input required type="email" name="email" class="form-control" placeholder="Email*">
                            </div>
                            <br>
                            <div class="input-group login-input">
                                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                <input required type="password" name="pass" class="form-control" placeholder="Password*">
                            </div>
                            <br>
                            <div class="input-group login-input">
                                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                <input required type="password" name="repass" class="form-control" placeholder="Repeat the password*">
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-ar btn-primary pull-left">Register</button>
                                    &nbsp;&nbsp;&nbsp;If you already have an account, you can <a href="{% url 'app:signin' %}">login here</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'app/assets/js/vendors.js' %}"></script>
<script src="{% static 'app/assets/js/syntaxhighlighter/shCore.js' %}"></script>
<script src="{% static 'app/assets/js/app.js' %}"></script>
<script src="{% static 'app/assets/js/holder.js' %}"></script>
<script src="{% static 'app/js/home_login_full.js' %}"></script>
<script src="{% static 'app/js/notify.js' %}"></script>
{% if messages %}
    <script>
        jQuery(document).ready(function () {
            {% for message in messages %}
                jQuery.notify({
                    message: '{{ message }}'
                },{
                    type: 'danger',
                    placement: {
                        from: "top",
                        align: "center"
                    }
                });
            {% endfor %}
        });
    </script>
{% endif %}
</body>

</html>